### ISSUE TITLE
"important options" page has a broken link

### ISSUE THREAD

**Issue by mvdan** [tinygo-org/tinygo-site#126]
https://tinygo.org/usage/important-options/ contains:

> `Read [supported targets]() for a list of supported targets.`

Looks like the Markdown didn't render well there.

**Comment by aykevl** [comment]
Thank you! I have a fix here: https://github.com/tinygo-org/tinygo-site/pull/127

**Comment by deadprogram** [comment]
Oops forgot to close this when it was fixed. Thanks @mvdan for reporting and @aykevl for the correction.
