### ISSUE TITLE
Add documentation for the board as added in 0.16.0

### ISSUE THREAD

**Issue by sago35** [tinygo-org/tinygo-site#132]
* d1mini: add this ESP8266 based board
    * https://github.com/tinygo-org/tinygo/pull/1444
* esp32: use board definitions instead of chip names
    * https://github.com/tinygo-org/tinygo/pull/1439
* qtpy: add board definition for Adafruit QTPy
    * https://github.com/tinygo-org/tinygo/pull/1488
* teensy40: add this board
    * https://github.com/tinygo-org/tinygo/pull/1425
* wasi: add support for this target
    * https://github.com/tinygo-org/tinygo/pull/1373

**Comment by aykevl** [comment]
All these are merged, so closing.
