### ISSUE TITLE
Wasm example doesn't compile

### ISSUE THREAD

**Issue by rchernobelskiy** [tinygo-org/tinygo-site#139]
The go code on this page doesn't seem to compile:
https://tinygo.org/webassembly/webassembly/
I'm guessing it's because it imports `net/http`

**Comment by deadprogram** [comment]
I think the code you refer to is the golang server for the web page that would serve the webassembly. 

This webassembly would be compiled with TinyGo, and the web server run using standard Go. I realize that is not entirely clear from the instructions, so I will tag this issue using "docs".

**Comment by rchernobelskiy** [comment]
🤦 apologies should have paid more attention
