### ISSUE TITLE
Potential site reorganization

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo-site#144]
I have been thinking about some ways to reorganize the site.

https://documentation.divio.com/ could be a very interesting approach for us to take.

This issue is intended to start a discussion about how we can improve our documentation experience.

**Comment by Nerzal** [comment]
I just stumbled across this beauty of a documentation: 
https://developer.fyne.io/tour/introduction/

I especially like the "Tour" part. 
We allready have examples for all drivers in the driver repo and lots of examples in the tinygo repo itself. 
We could simply take some these examples, put them together in a tour, which also describes where to find the drivers repo etc. and lead the visitor through a tour of tinygo. We might also include the tinygo playground there :) 

I'm also a fan of the "Tour of Go" never had a better start in a new programming language.

**Comment by aykevl** [comment]
I fully agree with all the suggestions here. In my opinion, the tinygo.org website is a bit messy right now.

Specifically, I think we can reorganize it as follows:

Tutorials:

* (we don't have many tutorials yet, but I think a tour would fit well here)

How-to guides:

* IDE integration: https://tinygo.org/ide-integration/
* I think the page on interrupts (https://tinygo.org/compiler-internals/interrupts/) counts as a how-to guide.
* Same for Inline assembly (https://tinygo.org/compiler-internals/inline-assembly/).
* "Using WebAssembly": https://tinygo.org/webassembly/webassembly/

Reference guides:

* "Using TinyGo" - it describes the available subcommands and flags
* Perhaps the "Packages supported by TinyGo" page? Although it's also closely related to the "Go language features" page.
* "Go on microcontrollers" (https://tinygo.org/microcontrollers/), and especially the machine package documentation.

Explanation:

* Most of the pages under Compiler Internals are really background information not necessary for most people and thus explanation.
* "Go language features" seems like an explanatory page to me.

---

But maybe I'm approaching this the wrong way. Maybe it's better to start fresh in some way and copy / edit / write documentation as necessary.
Perhaps something like this: to get incremental benefits we can start with adding a tutorial section at the start (including a tour) alongside existing documentation. After that we can add a how-to section and move+cleanup existing pages over there, which also removes some main menu entries. Then perhaps we can add a new "Explanation" page where we move the explanatory pages in a similar way. Finally, perhaps, we can move the bulk of the pages (in content size): the references for all the boards and machine package variants.

Also, I would like to say that the theme isn't easy to navigate on desktop systems. The menu is a small rectangle in the bottom left that you have to scroll a lot: not good for usability.

**Comment by LiamRandall** [comment]
It would be nice to also have a "Using Tingo" site as well where orgs can share their enthusiasm for the project, logo exchange, etc.

**Comment by Nerzal** [comment]
So this is what a user sees, when visiting the page. 

![grafik](https://user-images.githubusercontent.com/9110370/113410393-97320980-93b3-11eb-9e51-b7648fd3bd05.png)

Yes, it is kind of informative, but does not look very exciting. 
How about adding a Tinygo in action segment at the bottom of that initial page? 
We could embed small gifs / short videos / images in a carousel or something like that, that show Blinking LEDs, running motors, displays etc. 

So something, that makes you want to try out TinyGo yourself.

**Comment by aykevl** [comment]
Yes, I absolutely agree. I think a good example could be an embedded [play.tinygo.org](https://play.tinygo.org/), which I hope to (eventually!) improve so that it can indeed have an attractive display of LEDs, displays, etc. Somewhat like the "Try Go" part on the right hand side of golang.org, but with output on simulated devices instead of (or in addition to) console output.

**Comment by soypat** [comment]
Here's TinyGo's look with `geekdoc` theme. Downside is you have to install a bunch of npm packages. Don't know where we stand on including npm stuff. I think it might lend itself to additional maintenance pains.

Edit: I think the fyne website should be the goal. It really is functional and pretty.

![image](https://user-images.githubusercontent.com/26156425/114577079-1a741a80-9c52-11eb-9906-51d48e671975.png)
![image](https://user-images.githubusercontent.com/26156425/114577366-51e2c700-9c52-11eb-90fe-c9b354fe7bf5.png)
![image](https://user-images.githubusercontent.com/26156425/114577406-5a3b0200-9c52-11eb-98f1-e4f260e8b113.png)

**Comment by deadprogram** [comment]
@soypat did you mean https://github.com/thegeeklab/hugo-geekdoc if so then https://geekdocs.de/usage/getting-started/#option-1-download-pre-build-release-bundle does not require installing any npm packages.

**Comment by soypat** [comment]
@deadprogram Yes, you're right. I was following the other steps on the repo page.

**Comment by deadprogram** [comment]
Please see https://github.com/tinygo-org/tinygo-site/pull/164 which has just been merged into `dev` branch.

I will now close this issue, in favor of opening specific new issues on the new structure and theme. Thank you everyone!
