### ISSUE TITLE
Build flag: opt=0 is not supported but documented

### ISSUE THREAD

**Issue by Nerzal** [tinygo-org/tinygo-site#147]
The [documentation](https://tinygo.org/usage/important-options/) states, that we can pass -opt=0 to deactivate optimization steps during build. But this is currently not true, as this option is commented out. 

So we should either remove it from documentation, or update the documentation with that info :) 

```go
	/*
		Currently, turning optimizations off causes compile failures.
		We rely on the optimizer removing some dead symbols.
		Avoid providing an option that does not work right now.
		In the future once everything has been fixed we can re-enable this.

		case "none", "0":
			errs = transform.Optimize(mod, config, 0, 0, 0) // -O0
	*/
```

**Comment by aykevl** [comment]
I have fixed the `-opt=0` issue here: https://github.com/tinygo-org/tinygo/pull/1689

**Comment by Nerzal** [comment]
Nice job :)

**Comment by ysoldak** [comment]
Fixed, close?

**Comment by aykevl** [comment]
Yes, this is now fixed in the latest release (with a test to avoid a regression).
