### ISSUE TITLE
The tinygo.org documentation is hard to read

### ISSUE THREAD

**Issue by arp242** [tinygo-org/tinygo-site#162]
On my Linux system in Firefox the documentation on tinygo.org isn't very comfterable to read:

![screenshot_2021-04-22-15-05-24_border](https://user-images.githubusercontent.com/1032692/115821612-b1e92280-a435-11eb-8408-a21a4f6bf28b.png)

It's not completely *unreadable*, but the thin font size in combination with the dark grey colour doesn't exactly give a comfterable reading experience either.

It may appear different on Windows or macOS; I didn't test as I don't have a Windows or macOS machine readily available.

It's not the biggest issue in the world, but I think a bit of tweaking might not be a bad idea, e.g. by choosing a different webfont. I don't mind trying out a few things and submitting a PR if people agree this is something that needs addressing.

If I remove the `font-weight: 300` it's a bit better, although the font is a bit ugly:

![screenshot_2021-04-22-15-05-44_border](https://user-images.githubusercontent.com/1032692/115821617-b3b2e600-a435-11eb-918a-0c00bf3a3a70.png)

Setting the colour to `#000` also improves it a bit:

![screenshot_2021-04-22-15-07-16_border](https://user-images.githubusercontent.com/1032692/115821621-b4e41300-a435-11eb-8585-621febc82d43.png)

This is how it looks with just the default `sans-serif` font (DejaVu Sans), which IMHO is much better than of the above:

![screenshot_2021-04-22-15-08-05_border](https://user-images.githubusercontent.com/1032692/115821624-b57ca980-a435-11eb-8c59-047d38ef4495.png)

**Comment by deadprogram** [comment]
Please see https://github.com/tinygo-org/tinygo-site/pull/164 which has just been merged into `dev` branch.

**Comment by deadprogram** [comment]
Closing since we have had a new site for some weeks now. Please reopen if needed. Thanks.

**Comment by arp242** [comment]
Looks great now; thanks!
