### ISSUE TITLE
Docker usage instructions link missing

### ISSUE THREAD

**Issue by johanbrandhorst** [tinygo-org/tinygo-site#17]
The link to the instructions for how to run tinygo with Docker from the installation page is 404ing:

https://tinygo.org/getting-started/linux/
(see bottom of page).

We should update the docs with the new docker image in mind. Here's a oneliner I've successfully used to build and copy the relevant wasm files that can be used for inspiration:

```
docker run --rm -v $$(pwd):/go/src/github.com/johanbrandhorst/wasm-experiments tinygo/tinygo:0.5.0 /bin/bash -c "\
	cd /go/src/github.com/johanbrandhorst/wasm-experiments && \
	tinygo build -o ./html/test.wasm -target wasm --no-debug ./$(target)/main.go && \
	cp /usr/local/tinygo/targets/wasm_exec.js ./html/wasm_exec.js\
"
```
(From https://github.com/johanbrandhorst/wasm-experiments/blob/6d867a75ab1291a26cc1af5ae2655d82e9f88af3/Makefile#L8).

**Comment by deadprogram** [comment]
The first part of this was addressed in https://github.com/tinygo-org/tinygo-site/commit/4d351c6606d34e18049bfe00d93a0bc525e71a55

The other, how about a PR that makes those changes? Seems like a good idea.

**Comment by johanbrandhorst** [comment]
Great, I'll see what I can do
