### ISSUE TITLE
Dead links to tinygo docs

### ISSUE THREAD

**Issue by saper** [tinygo-org/tinygo-site#190]
All links referred from https://github.com/f-secure-foundry/tamago/wiki/Frequently-Asked-Questions-(FAQ)#tinygo have gone missing...

Would there be a possibility to restore them, possibly with redirects or something?

**Comment by aykevl** [comment]
I made a PR to fix this with redirects.

**Comment by saper** [comment]
Thank you, it works fine now! That was quick!
