### ISSUE TITLE
installation instructions still show v0.18.0

### ISSUE THREAD

**Issue by soypat** [tinygo-org/tinygo-site#200]
Installation instruction still show old 0.18.0 version
i.e. Linux:
```
wget https://github.com/tinygo-org/tinygo/releases/download/v0.18.0/tinygo_0.18.0_amd64.deb
sudo dpkg -i tinygo_0.18.0_amd64.deb
```

**Comment by sago35** [comment]
Thank you.
I've just fixed it and merged it into the release branch as well.

https://tinygo.org/getting-started/install/linux/
