### ISSUE TITLE
Differences from Go: confusing indentation

### ISSUE THREAD

**Issue by Avokadoen** [tinygo-org/tinygo-site#211]
There seems like there is a list indentation error from the description.

> 
> - ...
> - Global variables are computed during compilation whenever possible (unlike Go, which does not have the equivalent of a .data section). This is an important optimization for several reasons: _**the following elements should be indented to indicate a sub list**_
> - Startup time is reduced. This is nice, but not the main reason.
> - ...
>

**Comment by aykevl** [comment]
Thank you! The information is there, it's just that the list was not correctly formatted. I've made a PR to fix this: https://github.com/tinygo-org/tinygo-site/pull/212

**Comment by Avokadoen** [comment]
Good job! 😄

**Comment by deadprogram** [comment]
Fixed, thanks for pointing this out @Avokadoen
