### ISSUE TITLE
Installing older versions with Homebrew

### ISSUE THREAD

**Issue by drwpow** [tinygo-org/tinygo-site#222]
I’d like to downgrade tinygo to a previous version. Tried `brew install tinygo@0.20.0` but it couldn’t find the formula. What is the recommended way to install old versions on macOS? Could there be a “releases” page with previous releases or something?

**Comment by aykevl** [comment]
You can find older releases here, including binaries: https://github.com/tinygo-org/tinygo/releases

**Comment by drwpow** [comment]
Oh right—I was more wondering how to get Homebrew to link these older versions properly (Homebrew no longer supports installing from an arbitrary URL).

I ended up just taking an old [tinygo.rb](https://github.com/tinygo-org/homebrew-tools/blob/master/tinygo.rb) version I wanted, saving it locally, and installing that

**Comment by aykevl** [comment]
I don't know. I haven't looked into that. If you want, you can investigate whether it's possible to add support for this in the tinygo.rb file and make a PR? (It might not be possible with Homebrew: again, I don't know a lot about it).

**Comment by drwpow** [comment]
I _think_ it may just be as simple as just adding all the backversions as separate files, e.g.:

```
- tinygo.rb # current version
- tinygo@0.21.0.rb
- tinygo@0.20.0.rb
- tinygo@0.19.0.rb
- … 
```

But I will look more into it and submit a PR if there’s an easy fix

**Comment by drwpow** [comment]
I looked at other formulae and there aren’t many that do this (they’ll only add major versions, such as `python@2` or `node@14`). I think this would just add noise/maintenance and this probably isn’t a super common thing.

In case other people find this, to expand on [my earlier comment](https://github.com/tinygo-org/tinygo-site/issues/222#issuecomment-982030487), here’s how I did it

1. Find [the previous version of tinygo.rb you’d like to install](https://github.com/tinygo-org/homebrew-tools/commits/master/tinygo.rb)
2. Save it locally anywhere (e.g. `~/Desktop/tinygo.rb`)
3. `brew install` that local file (e.g. `brew install ~/Desktop/tinygo.rb`)
