### ISSUE TITLE
cannot find package "unsafe" and defining GOROOT

### ISSUE THREAD

**Issue by supcik** [tinygo-org/tinygo-site#24]
I installed go using homebrew on macos and I currently have the version 1.12.5.

When I run tinygo, I got the following error:

```
error: cannot find package "unsafe" in any of:
   /usr/local/Cellar/go/1.11.1/libexec/src/unsafe (from $GOROOT)
   /<HOME>/go/src/unsafe (from $GOPATH)
```

I don't have any GOROOT defined in my environment.

I was able to solve this issue by defining GOROOT while using tinygo:

```
GOROOT=$(go env GOROOT) tinygo ...
```

As I also had to extend PATH, here is my final workaround:

```
PATH=/usr/local/Cellar/llvm/8.0.0/bin:$PATH GOROOT=$(go env GOROOT) tinygo ...
```

N.B. Using `$(go env GOROOT)` works in zsh and in bash, but it might not work with all shells (e.g fish).

**Comment by deadprogram** [comment]
Hi @supcik that was corrected by https://github.com/tinygo-org/tinygo/pull/330 which will be part of the next TinyGo release. Thanks!

**Comment by supcik** [comment]
OK. Thank you for the update. So I guess that you can ignore the PR.

**Comment by justinclift** [comment]
Depends which goes live first, the FAQ entry or the next TinyGo release. :smile:

**Comment by deadprogram** [comment]
The fix in TinyGo itself was merged a while ago, but this PR was not closed in a timely way, sorry about that. Now closing, thanks again for the help!
