### ISSUE TITLE
Using PWM Tutorial Document

### ISSUE THREAD

**Issue by s-fairchild** [tinygo-org/tinygo-site#257]
Hello,

I am attempting to follow the [PWM Tutorial](https://tinygo.org/docs/tutorials/pwm/) and it looks like this function name has changed?
I'm unable to find a function definition for NewPWM in my tinygo/src directory.

```bash
[steven@fedora tinypwm]$ grep -iR NewPWM
/usr/lib64/tinygo/src/
[steven@fedora tinypwm]$
```
![Tinygo Docs issue PWM 2022-04-13 21-13-45](https://user-images.githubusercontent.com/67697325/163295400-8d891ec0-29ea-47c4-861c-f555f6027ffd.png)

**Comment by deadprogram** [comment]
See https://github.com/tinygo-org/tinygo-site/pull/260

**Comment by s-fairchild** [comment]
@deadprogram thank you!
