### ISSUE TITLE
Add link to platform specific installations in getting started

### ISSUE THREAD

**Issue by karuppiah7890** [tinygo-org/tinygo-site#27]
Currently the links are on the left navigation bar. I think it would be great to have the links on this page too - https://github.com/tinygo-org/tinygo-site/blob/master/content/getting-started/_index.md 

I will raise a PR for the same?

**Comment by justinclift** [comment]
Yeah, the blank "contents" of these header pages keeps on catching me out too.

It's probably a good idea to put suitable stuff in that blank area. :smile:

**Comment by karuppiah7890** [comment]
I just put links currently and raised a PR #28 . Let me know if you want to add something more. May be some image to fill up the blank area? 😉

**Comment by karuppiah7890** [comment]
Like an image of blinking light in a circuit board ?

**Comment by justinclift** [comment]
Sounds reasonable. :smile:

Note - If using an image, we need to make sure the image is suitably licenced.  Just saying. :wink:

**Comment by karuppiah7890** [comment]
Ah, yeah. I will check for such photos. Also I will see if I can get free images of all the circuit boards that tinygo currently supports.

**Comment by justinclift** [comment]
> I will see if I can get free images of all the circuit boards that tinygo currently supports

Sounds like a plan. :smile:
