### ISSUE TITLE
Wrong URL https://tinygo.org/docs/reference/microcontrollers/esp8266-nodemcu

### ISSUE THREAD

**Issue by xvoland** [tinygo-org/tinygo-site#286]
https://tinygo.org/docs/reference/microcontrollers/esp8266-nodemcu

Link to the page is wrong

**Comment by bxparks** [comment]
There is no longer any reference to the string "esp8266-nodemcu" in the docs. My guess is that this was fixed in 90a3fd3150119fc07f4a2ccc0da59abf65ed0fce on Thu Dec 1 22:00:57 2022 to point to https://tinygo.org/docs/reference/microcontrollers/nodemcu instead.

**Comment by aykevl** [comment]
Closing, as this appears to be fixed.
