### ISSUE TITLE
Binary package for ARM-based linux is not found

### ISSUE THREAD

**Issue by cheung-chifung** [tinygo-org/tinygo-site#29]
I can not download the file which is listed on the document, seems it's hasn't been uploaded successfully.

`wget https://github.com/tinygo-org/tinygo/releases/download/v0.6.0/tinygo_0.6.0_armhf.deb
sudo dpkg -i tinygo_0.6.0_armhf.deb`

**Comment by justinclift** [comment]
Good catch. :smile:

**Comment by aykevl** [comment]
I didn't have time at the release and then forgot about it. I've build an ARM build and uploaded.

**Comment by justinclift** [comment]
@cheung-chifung Do you have time to check and confirm the package is working for you now? :smile:

**Comment by cheung-chifung** [comment]
It works for me. Thank you. 😁
