### ISSUE TITLE
Using WASI page needed

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo-site#306]
We need to add a page for using TinyGo with WASI similar to https://tinygo.org/docs/guides/webassembly/ probably under https://tinygo.org/docs/guides/webassembly/wasi and to put the content on the current page under "Browser" aka https://tinygo.org/docs/guides/webassembly/browser

**Comment by deadprogram** [comment]
See https://github.com/tinygo-org/tinygo-site/pull/352

**Comment by mar1n3r0** [comment]
Can wasi be run in the browser?

**Comment by deadprogram** [comment]
This was previously released so now closing. Thank you!
