### ISSUE TITLE
add 'scoop install binaryen' for Windows install

### ISSUE THREAD

**Issue by mjcc30** [tinygo-org/tinygo-site#310]
Hi,
When i run this command on windows it fail
$ tinygo build -o main.wasm -target=wasi main.go
error: could not find wasm-opt, set the WASMOPT environment variable to override

So i have to install binaryen toolchain to get it works
$  scoop install binaryen

Can you add this to your documentation ?

**Comment by deadprogram** [comment]
This was previously released, so now closing. Thanks!
