### ISSUE TITLE
Docker usage instrauction is failed when tinygo is not installed

### ISSUE THREAD

**Issue by neko-suki** [tinygo-org/tinygo-site#35]
The following error is shown when I follow a docker usage instruction without installing tingyo. 

```
$ ls $GOPATH/bin | grep tinygo
$ docker run -v $GOPATH:/go -e "GOPATH=/go" tinygo/tinygo tinygo build -o /go/src/github.com/myuser/myrepo/wasm.wasm -target wasm --no-debug /go/src/github.com/myuser/myrepo/wasm-main.go
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"tinygo\": executable file not found in $PATH": unknown.
ERRO[0001] error waiting for container: context canceled 
```

I think `$GOPATH` is mounted to `/go` inside a docker container and installed `/go/tinygo` in the docker container will be overwritten. So, If I don't build tinygo, tinygo is unavailable. 

To replace `-v $GOPATH:go` with `-v $GOPATH/src:/go/src` can solve this issue. 

```
$ docker run -v $GOPATH/src:/go/src -e "GOPATH=/go" tinygo/tinygo tinygo build -o /go/src/github.com/myuser/myrepo/wasm.wasm -target wasm --no-debug /go/src/github.com/myuser/myrepo/wasm-main.go
```

In that case, `github.com/tinygo-org/tinygo` should be placed in `$GOPATH/src`, otherwise the following error is shown.

```
$ docker run -v $GOPATH/src:/go/src -e "GOPATH=/go" tinygo/tinygo tinygo build -o /go/src/github.com/myuser/myrepo/wasm.wasm -target wasm --no-debug /go/src/github.com/myuser/myrepo/wasm-main.go
error: could not autodetect root directory, set the TINYGOROOT environment variable to override
```

**Comment by deadprogram** [comment]
Looking at the Docker builds, as the automatic builds are currently broken. Not sure if what you are reporting has any relation...

**Comment by deadprogram** [comment]
I have updated the install info for the Docker image to specify version 0.7.1.

I suggest you do a `docker pull tinygo/tinygo:0.7.1` then try the defaults again, but using the latest image:

Test that you have it:

```
$ docker run tinygo/tinygo:0.7.1 tinygo version
tinygo version 0.7.1 linux/amd64
```

Then try running the command in the example, but using the `0.7.1` image:

```
$ docker run -v $GOPATH:/go -e "GOPATH=/go" tinygo/tinygo:0.7.1 tinygo build -o /go/src/github.com/myuser/myrepo/wasm.wasm -target wasm --no-debug /go/src/github.com/myuser/myrepo/wasm-main.go
error: open /go/src/github.com/myuser/myrepo/wasm-main.go: no such file or directory
```

You should see a "no such file or directory", which would be correct, since you also need to point to whatever TinyGo file you want to compile.

Hope that helps!

**Comment by neko-suki** [comment]
Using `0.7.1` solved the problem what I faced. Thank you very much!
