### ISSUE TITLE
Fix Diverged Histories of dev and release branch

### ISSUE THREAD

**Issue by sago35** [tinygo-org/tinygo-site#409]
There is no difference between ① and ②. However, the histories of dev and release have diverged. I would like to fix this by performing one of the following actions. What do you think?

![image](https://github.com/tinygo-org/tinygo-site/assets/9251039/eb60d9b9-6b6b-4cc9-8c1b-c5595a9fb95f)

1. `git checkout dev && git merge origin/release`
2. `git checkout dev && git reset --hard origin/release`

**Comment by deadprogram** [comment]
I think I have now taken care of this, @sago35 thanks for pointing it out!
