### ISSUE TITLE
Devices - attempting to use the 'edit this page' link on the right, results in a 404

### ISSUE THREAD

**Issue by nickaxgit** [tinygo-org/tinygo-site#414]
Would like to highlight to people the availability of the 'examples' folder for devices ..  but unable to edit the main branch version of the docs

**Comment by nickaxgit** [comment]
on this page 

https://tinygo.org/docs/reference/devices/  

the link in the right side bar "edit this page"

**Comment by deadprogram** [comment]
Thanks for reporting @nickaxgit we'll take a look.

**Comment by deadprogram** [comment]
@nickaxgit please see #415 for a fix.

**Comment by deadprogram** [comment]
Now fixed, thanks for reporting @nickaxgit
