### ISSUE TITLE
When will you guys be compiling the tinygo compiler targetting WASM?

### ISSUE THREAD

**Issue by jymchng** [tinygo-org/tinygo-site#421]
Hi, thank you for the great awesome work!

I think it will be a great feature if the tinygo compiler itself is compiled and targetting WASM so that people can start writing and running arbitrary Go codes on the browser.

🤭👍

**Comment by aykevl** [comment]
Right now TinyGo is compiled using the Go toolchain, which supports WebAssembly but doesn't support CGo at the same time. So this is not currently possible. 
See: https://github.com/golang/go/issues/55351

It would be really nice to have this though! It could also make things like the VSCode TinyGo extension better.

**Comment by deadprogram** [comment]
Closing since no action required. Thanks!
